### ISSUE TITLE
How to configure CACHE_VIRT_SIZE and CACHE_PHY_SIZE?

### ISSUE THREAD

**Issue by dangzzz** [thu-pacman/TriCache#1]
Hi, I'm really impressed with how solid your work is.
I have some questions about how to configure the CACHE_VIRT_SIZE and CACHE_PHY_SIZE  to fit my sever when running the code. 

In particular, why do you divide $i by 8 and add 48 in _run_ligra_cache_small.sh_? Why the CACHE_VIRT_SIZE is set to 32 T?
```
    export CACHE_VIRT_SIZE=$(expr 32 \* 1024 \* 1024 \* 1024 \* 1024  )
    ......
    echo $(expr \( $i \/ 8 + 48 \) \* 1024 \* 1024 \* 1024) | sudo tee /sys/fs/cgroup/limit/memory.max
    export CACHE_PHY_SIZE=$(expr \( $i - $i \/ 8 - 48 \) \* 1024 \* 1024 \* 1024 )
```

Could you please guide me in finding answers for these questions? Thanks in advance.

**Comment by jiguanglizipao** [comment]
CACHE_VIRT_SIZE is the size of the TriCache virtual memory, so it can be configured to the total size of the disk.
CACHE_PHY_SIZE is the physical memory used by the TriCache buffers, so keep it in your main memory (and leave some memory for the page table).

In our evaluation, we want to limit the memory usage to some restrictions, like 64GB, which requires us to fine tune CACHE_PHY_SIZE (the size of the TriCache buffer).
The code about "$i divided by 8 plus 48" is used to calculate how much memory should be used outside of TriCache (including page tables and Ligra's temporary buffers), and the rest ($i - $I / 8 - 48) is used as a buffer for the disk. You can see more configurations for different memory usage like 64GB/16GB in run_ligra_cache.sh, and they might be useful.

**Comment by dangzzz** [comment]
Thanks for your response. I now can run the code on my server. I still have a question for _setup_spdk.sh_, which is used to set up DMA memory for SPDK. Is the physical memory used by the TriCache buffers fully contained in that DMA memory, which also means CACHE_PHY_SIZE needs to be no larger than the DMA memory size? If I want to utilize all the physical memory on my server for running the code, I should make the CACHE_PHY_SIZE (or DMA memory size) plus the size of the memory outside of TriCache equal to the total memory size of my server, right?

**Comment by jiguanglizipao** [comment]
Yes, CACHE_PHY_SIZE should be smaller than the DMA memory size. Yes, that is correct.

**Comment by dangzzz** [comment]
Thank you very much!
